
# URLs
STEAM_ID_LINK = "https://www.steamidfinder.com/lookup/"
GAME_TAGS_LINK = "https://www.lorenzostanco.com/lab/steam/u/"
STEAM_PROFILE_URL = "https://steamcommunity.com/my"
STEAM_PLACEHOLDER_URL = "https://steamcommunity.com/profiles/12345678"
STEAM_ID_URL = "https://steamcommunity.com/profiles/"

ELUX_ID_TEMP = "76561198096871136"


WEBPAGE_WAIT_TIME = 15

UPPER_LIMIT = 200
LOWER_LIMIT = 100

UPPER_MAX_BATCH = 20
LOWER_MAX_BATCH = 10

SCALING_FACTOR = 10

MIN_BATCH = 3 #probably not needed anymore, unless we want to implement like a last pick scenario

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 500
BORDER_WIDTH = 5
SCREEN_TITLE = "Steam Game Picker"
PRIMARY_COLOR = "#282828"
SECONDARY_COLOR = "#323232"
THIRDARY_COLOR = "#f2f2f2"
ACENT_COLOR = "#46d39e"

# TEXT
DEFAULT_FONT = "Arial"
DEFAULT_FONT_SIZE = 18
HEADER_FONT_SIZE = 25
SMALL_FONT_SIZE = 10
TITLE_TEXT_PADDING_Y = 65
LABEL_PADDING_Y = 15
GAME_OBJECT_PADDING_Y = LABEL_PADDING_Y * 3
DISTANCE_FROM_WEST_WALL = 30
CHECKLIST_BOTTOM_Y_PATTING = 0
CHECKLIST_TOP_Y_PATTING = 50
CHECKLIST_MAX_CHAR_LENGTH = 11
GAME_LIST_FRAM_PADDING = 3

GRID_MAX_COLUMS = 3
